WITH mapping(name, roles) AS (
  VALUES
    ('Aatrox', ARRAY['top','jungle']),
    ('Ahri', ARRAY['mid']),
    ('Akali', ARRAY['mid','top']),
    ('Akshan', ARRAY['mid','top']),
    ('Alistar', ARRAY['support']),
    ('Ambessa', ARRAY['jungle','top']),
    ('Amumu', ARRAY['jungle','support']),
    ('Anivia', ARRAY['mid']),
    ('Annie', ARRAY['mid','support']),
    ('Aphelios', ARRAY['adc']),
    ('Ashe', ARRAY['adc','support']),
    ('Aurelion Sol', ARRAY['mid']),
    ('Aurora', ARRAY['mid','top']),
    ('Azir', ARRAY['mid']),
    ('Bard', ARRAY['support']),
    ('Bel''Veth', ARRAY['jungle']),
    ('Blitzcrank', ARRAY['support']),
    ('Brand', ARRAY['support','mid']),
    ('Braum', ARRAY['support']),
    ('Briar', ARRAY['jungle','top']),
    ('Caitlyn', ARRAY['adc']),
    ('Camille', ARRAY['top']),
    ('Cassiopeia', ARRAY['mid','top']),
    ('Cho''Gath', ARRAY['top','mid']),
    ('Corki', ARRAY['mid','adc']),
    ('Darius', ARRAY['top']),
    ('Diana', ARRAY['jungle','mid']),
    ('Dr. Mundo', ARRAY['top','jungle']),
    ('Draven', ARRAY['adc']),
    ('Ekko', ARRAY['jungle','mid']),
    ('Elise', ARRAY['jungle']),
    ('Evelynn', ARRAY['jungle']),
    ('Ezreal', ARRAY['adc']),
    ('Fiddlesticks', ARRAY['jungle','support']),
    ('Fiora', ARRAY['top']),
    ('Fizz', ARRAY['mid']),
    ('Galio', ARRAY['mid','support']),
    ('Gangplank', ARRAY['top']),
    ('Garen', ARRAY['top']),
    ('Gnar', ARRAY['top']),
    ('Gragas', ARRAY['top','jungle','mid','support']),
    ('Graves', ARRAY['jungle','top']),
    ('Gwen', ARRAY['top','jungle']),
    ('Hecarim', ARRAY['jungle']),
    ('Heimerdinger', ARRAY['mid','support']),
    ('Hwei', ARRAY['mid']),
    ('Illaoi', ARRAY['top']),
    ('Irelia', ARRAY['top','mid']),
    ('Ivern', ARRAY['jungle','support']),
    ('Janna', ARRAY['support']),
    ('Jarvan IV', ARRAY['jungle','support']),
    ('Jax', ARRAY['top','jungle']),
    ('Jayce', ARRAY['top','mid']),
    ('Jhin', ARRAY['adc']),
    ('Jinx', ARRAY['adc']),
    ('K''Sante', ARRAY['top']),
    ('Kai''Sa', ARRAY['adc']),
    ('Kalista', ARRAY['adc']),
    ('Karma', ARRAY['support','mid','top']),
    ('Karthus', ARRAY['jungle','adc']),
    ('Kassadin', ARRAY['mid']),
    ('Katarina', ARRAY['mid']),
    ('Kayle', ARRAY['top','mid']),
    ('Kayn', ARRAY['jungle']),
    ('Kennen', ARRAY['top','mid']),
    ('Kha''Zix', ARRAY['jungle']),
    ('Kindred', ARRAY['jungle']),
    ('Kled', ARRAY['top']),
    ('Kog''Maw', ARRAY['adc']),
    ('LeBlanc', ARRAY['mid']),
    ('Lee Sin', ARRAY['jungle']),
    ('Leona', ARRAY['support']),
    ('Lillia', ARRAY['jungle','top']),
    ('Lissandra', ARRAY['mid']),
    ('Lucian', ARRAY['adc','mid']),
    ('Lulu', ARRAY['support']),
    ('Lux', ARRAY['support','mid']),
    ('Malphite', ARRAY['top','support']),
    ('Malzahar', ARRAY['mid']),
    ('Maokai', ARRAY['support','jungle','top']),
    ('Master Yi', ARRAY['jungle']),
    ('Mel', ARRAY['mid']),
    ('Milio', ARRAY['support']),
    ('Miss Fortune', ARRAY['adc']),
    ('Mordekaiser', ARRAY['top','jungle']),
    ('Morgana', ARRAY['support','jungle']),
    ('Naafiri', ARRAY['mid']),
    ('Nami', ARRAY['support']),
    ('Nasus', ARRAY['top']),
    ('Nautilus', ARRAY['support','jungle']),
    ('Neeko', ARRAY['mid','support']),
    ('Nidalee', ARRAY['jungle']),
    ('Nilah', ARRAY['adc']),
    ('Nocturne', ARRAY['jungle','top']),
    ('Nunu & Willump', ARRAY['jungle']),
    ('Olaf', ARRAY['top','jungle']),
    ('Orianna', ARRAY['mid']),
    ('Ornn', ARRAY['top']),
    ('Pantheon', ARRAY['support','mid','top','jungle']),
    ('Poppy', ARRAY['jungle','top','support']),
    ('Pyke', ARRAY['support','mid']),
    ('Qiyana', ARRAY['mid','jungle']),
    ('Quinn', ARRAY['top']),
    ('Rakan', ARRAY['support']),
    ('Rammus', ARRAY['jungle']),
    ('Rek''Sai', ARRAY['jungle']),
    ('Rell', ARRAY['support','jungle']),
    ('Renata Glasc', ARRAY['support']),
    ('Renekton', ARRAY['top']),
    ('Rengar', ARRAY['jungle','top']),
    ('Riven', ARRAY['top']),
    ('Rumble', ARRAY['top','jungle','mid']),
    ('Ryze', ARRAY['mid','top']),
    ('Samira', ARRAY['adc']),
    ('Sejuani', ARRAY['jungle','top']),
    ('Senna', ARRAY['support','adc']),
    ('Seraphine', ARRAY['support','adc','mid']),
    ('Sett', ARRAY['top','support']),
    ('Shaco', ARRAY['jungle','support']),
    ('Shen', ARRAY['top','support']),
    ('Shyvana', ARRAY['jungle','top']),
    ('Singed', ARRAY['top']),
    ('Sion', ARRAY['top']),
    ('Sivir', ARRAY['adc']),
    ('Skarner', ARRAY['jungle','top']),
    ('Smolder', ARRAY['adc','mid']),
    ('Sona', ARRAY['support']),
    ('Soraka', ARRAY['support']),
    ('Swain', ARRAY['support','adc','mid','top']),
    ('Sylas', ARRAY['mid','top','jungle']),
    ('Syndra', ARRAY['mid']),
    ('Tahm Kench', ARRAY['support','top']),
    ('Taliyah', ARRAY['jungle','mid','support']),
    ('Talon', ARRAY['mid','jungle']),
    ('Taric', ARRAY['support']),
    ('Teemo', ARRAY['top']),
    ('Thresh', ARRAY['support']),
    ('Tristana', ARRAY['adc','mid']),
    ('Trundle', ARRAY['jungle','top','support']),
    ('Tryndamere', ARRAY['top','mid']),
    ('Twisted Fate', ARRAY['mid']),
    ('Twitch', ARRAY['adc','support']),
    ('Udyr', ARRAY['jungle','top']),
    ('Urgot', ARRAY['top']),
    ('Varus', ARRAY['adc']),
    ('Vayne', ARRAY['adc','top']),
    ('Veigar', ARRAY['mid','support']),
    ('Vel''Koz', ARRAY['support','mid']),
    ('Vex', ARRAY['mid']),
    ('Vi', ARRAY['jungle']),
    ('Viego', ARRAY['jungle']),
    ('Viktor', ARRAY['mid']),
    ('Vladimir', ARRAY['mid','top']),
    ('Volibear', ARRAY['jungle','top']),
    ('Warwick', ARRAY['jungle','top']),
    ('Wukong', ARRAY['jungle','top']),
    ('Xayah', ARRAY['adc']),
    ('Xerath', ARRAY['support','mid']),
    ('Xin Zhao', ARRAY['jungle']),
    ('Yasuo', ARRAY['mid','top','adc']),
    ('Yone', ARRAY['mid','top']),
    ('Yorick', ARRAY['top']),
    ('Yuumi', ARRAY['support']),
    ('Yunara', ARRAY['adc']),
    ('Zaahen', ARRAY['top','jungle']),
    ('Zac', ARRAY['jungle','top','support']),
    ('Zed', ARRAY['mid','jungle']),
    ('Zeri', ARRAY['adc']),
    ('Ziggs', ARRAY['adc','mid']),
    ('Zilean', ARRAY['support','mid']),
    ('Zoe', ARRAY['mid']),
    ('Zyra', ARRAY['support','jungle'])
)
INSERT INTO champion_roles (champion_id, role)
SELECT c.id, r.role
FROM mapping m
JOIN champions c ON c.name = m.name
CROSS JOIN LATERAL unnest(m.roles) AS r(role)
ON CONFLICT DO NOTHING;